### PR TITLE
Corrected HTTP response code for Model version does not exists exception

### LINKED ISSUE #196: Attempting to set default version to nonexistent version number gives exception in log and HTTP 500
**Repro:** Given the model archives `r18_v1.0.mar` and `r18_v1.1.mar`, which contain versions `v1.0` and `v1.1` respectively of model `r18`, bring up a TorchServe instance with no models running, and run the following commands:

```
curl -X POST "http://localhost:8081/models?url=r18_v1.0.mar&initial_workers=1"
curl -X POST "http://localhost:8081/models?url=r18_v1.1.mar&initial_workers=1"
curl -X PUT http://localhost:8081/models/r18/1.1/set-default
```

Note that the `/set-default` API call specifies model version `1.1`, not `v1.1`.

Log shows the following:

```
2020-04-13 17:30:39,110 [WARN ] epollEventLoopGroup-3-5 org.pytorch.serve.wlm.ModelManager - Model r18 version 1.1 not found.
2020-04-13 17:35:02,594 [WARN ] epollEventLoopGroup-3-6 org.pytorch.serve.wlm.ModelManager - Model version 1.1 does not exist for model r18
2020-04-13 17:35:02,595 [ERROR] epollEventLoopGroup-3-6 org.pytorch.serve.http.HttpRequestHandler -
org.pytorch.serve.http.InvalidModelVersionException: Model version 1.1 does not exist for model r18
        at org.pytorch.serve.http.ManagementRequestHandler.setDefaultModelVersion(ManagementRequestHandler.java:383)
        at org.pytorch.serve.http.ManagementRequestHandler.handleRequest(ManagementRequestHandler.java:82)
        at org.pytorch.serve.http.ApiDescriptionRequestHandler.handleRequest(ApiDescriptionRequestHandler.java:37)
        at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:42)
        at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:19)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

And the HTTP response is:

```
{
  "code": 500,
  "type": "InvalidModelVersionException",
  "message": "Model version 1.1 does not exist for model r18"
}
```

On the other hand, doing the same procedure, but with an unreg call:

```
curl -X DELETE http://localhost:8081/models/r18/1.1
```

...gives this log output:

```
2020-04-13 17:37:59,560 [WARN ] epollEventLoopGroup-3-7 org.pytorch.serve.wlm.ModelManager - Model r18 version 1.1 not found.
2020-04-13 17:37:59,560 [INFO ] epollEventLoopGroup-3-7 ACCESS_LOG - /127.0.0.1:37710 "DELETE /models/r18/1.1 HTTP/1.1" 400 0
2020-04-13 17:37:59,560 [INFO ] epollEventLoopGroup-3-7 TS_METRICS - Requests4XX.Count:1|#Level:Host|#hostname:ip-172-31-4-241,timestamp:null
```

...and this HTTP response:

```
{
  "code": 400,
  "type": "ModelVersionNotFoundException",
  "message": "Model version: 1.1 not found for model: r18"
}
```

The 400 is preferable; it says the error is on the user's side (asking for a bogus version) rather than a 500, which says the problem is on the server. Also, TorchServe should handle the error gracefully in both cases, and not show exceptions in the logs. (Ideally, they'd even be calling the same utility function to check the validity of the version.)

**Suggested remediation:** ___Standardize model version checking___ across calls that have a required or optional model version number argument (with no exception thrown). If a call specifies a nonexistent version, responses for all such calls should ___give a consistent HTTP response in the 4xx range.___

### PR DESCRIPTION
**Pull request by dkasar-aws**
## Description
Standardise "Model version not  found." response for all applicable Api's with Http status code 404.
Added UT for model version does not exists test scenarios for various Api's.
Updated OpenApi  responses.

Fixes #196 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Given the model archives r18_v1.0.mar and r18_v1.1.mar, which contain versions v1.0 and v1.1 respectively of model r18, bring up a TorchServe instance with no models running, and run the following commands:

```
curl -X POST "http://localhost:8081/models?url=r18_v1.0.mar&initial_workers=1"
curl -X POST "http://localhost:8081/models?url=r18_v1.1.mar&initial_workers=1"

```
- [x] Test A : attempt to set-default model of non existing model version  
  run cmd ``` curl -X PUT http://localhost:8081/models/r18/1.1/set-default```

Expected:
```
{
  "code": 404,
  "type": "ModelVersionNotFoundException",
  "message": "Model version 1.1 does not exist for model r18"
}
```
similar response is expected for other apis where in request model version is specified but that version does not exist.
- scale workers api : curl -X PUT "http://localhost:8081/models/r18/1.1?min_worker=2"    
- unregister api : curl -X  DELETE "http://localhost:8081/models/r18/1.1"  
- describe specific model api : curl -X GET "http://localhost:8081/models/r18/1.1"  
- inference api for r18 model

- [x] Test B: Attempt to delete default version
run ``` curl -X  DELETE "http://localhost:8081/models/r18/v1.0"```
Expected : 
```
{
  "code": 403,
  "type": "InvalidModelVersionException",
  "message": "Cannot remove default version for model r18"
}
```

- Logs
[issue_196_torchserve_sanity_log.txt](https://github.com/pytorch/serve/files/4585481/issue_196_torchserve_sanity_log.txt)

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 1]
```diff
@@ -270,13 +270,14 @@ private void handleUnregisterModel(
...
-                            "Model version: %s not found for model: %s", modelVersion, modelName));
+                            "Model version: %s does not exist for model: %s",
+                            modelVersion, modelName));
         } else if (httpResponseStatus == HttpResponseStatus.INTERNAL_SERVER_ERROR) {
             throw new InternalServerException("Interrupted while cleaning resources: " + modelName);
         } else if (httpResponseStatus == HttpResponseStatus.REQUEST_TIMEOUT) {
             throw new RequestTimeoutException("Timed out while cleaning resources: " + modelName);
         } else if (httpResponseStatus == HttpResponseStatus.FORBIDDEN) {
-            throw new InternalServerException(
+            throw new InvalidModelVersionException(
```
Comment (dhaniram-kshirsagar) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:280]: Should this be 'throw ModelVersionNotFoundException'? Also, let's keep only one class.

File: frontend/server/src/main/java/org/pytorch/serve/http/HttpRequestHandler.java [hunk 2]
```diff
@@ -61,6 +61,9 @@ protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest req) {
         } catch (OutOfMemoryError e) {
             logger.trace("", e);
             NettyUtils.sendError(ctx, HttpResponseStatus.INSUFFICIENT_STORAGE, e);
+        } catch (IllegalArgumentException e) {
+            logger.error("", e);
+            NettyUtils.sendError(ctx, HttpResponseStatus.FORBIDDEN, e);
```
Comment (dhaniram-kshirsagar) [inline frontend/server/src/main/java/org/pytorch/serve/http/HttpRequestHandler.java:66]: As per #196, it should be 404 and not 403. Why 403? Also, let's keep things simple i.e. Catch ModelVersionNotFound exception in NOT-FOUND if clause above instead of having base as illegalArgexception.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java [hunk 3]
```diff
@@ -426,7 +430,7 @@ private void testSetInvalidVersionDefault(String modelName, String defaultVersio
         TestUtils.getLatch().await();
 
         ErrorResponse resp = JsonUtils.GSON.fromJson(TestUtils.getResult(), ErrorResponse.class);
-        Assert.assertEquals(resp.getCode(), HttpResponseStatus.INTERNAL_SERVER_ERROR.code());
+        Assert.assertEquals(resp.getCode(), HttpResponseStatus.BAD_REQUEST.code());
```
Comment (dhaniram-kshirsagar) [inline frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:433]: I think it should be NOT_FOUND as commented above.

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java (hunk 1 above)
Comment (harshbafna) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:280]: InvalidModelVersionException for case where user tries to unregister the default version.

File: frontend/server/src/main/java/org/pytorch/serve/http/HttpRequestHandler.java (hunk 2 above)
Comment (harshbafna) [reply frontend/server/src/main/java/org/pytorch/serve/http/HttpRequestHandler.java:66]: ModelVersionNotFound extends ModelNotFound exception, which is already handled in the first catch block above. This is just an extra exception handling.

**Comment by harshbafna** [comment]
> @harshbafna @dhaniram-kshirsagar what's the resolution here? Also the branch is out of date

Updated exception handling and HTTP status response code in management and inference api handlers.
