### PR TITLE
Fix #1740: Handle OPTIONS in management API

### LINKED ISSUE #1740: CORS config not working
### 🐛 Describe the bug

I followed the [HuggingFace example](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers) to deploy the GPT2 model, but a CORS error occurred when the front-end was called.

I configured it in `config.properties` according to the [tutorial on the official website](https://pytorch.org/serve/configuration.html#configure-cross-origin-resource-sharing-cors), and then restarted the Docker container, but it didn't seem to work.

my `config.properties` file:
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store

cors_allowed_origin=*
cors_allowed_methods=GET, POST, PUT, DELETE
cors_allowed_headers=X-Custom-Header
```

inside Docker container:
image

The magic is that not all requests will report errors. The GET request to obtain the model list and the POST request to register the model will not report an error, but the PUT request to modify the model configuration and the DELETE request to delete the model will report an error. The most fatal thing is to make predictions. The POST request reports an error.

image

The front end uses axios to request to delete the model
```
      axios.delete(url + "/" + row["modelName"]).then(_ => {
        this.getTorchServeModelList();
      }).catch(err => {
        console.log(err);
      })
```

### Error logs

front-end request error:
image

### Installation instructions

```
docker pull pytorch/torchserve:latest-gpu
docker run --rm -it -d --name torchserve --gpus '"device=0"' -p 18080:8080 -p 18081:8081 -p 18082:8082 -p 17070:7070 -p 17071:7071 -v $(pwd)/config.properties:/home/model-server/config.properties -v $(pwd)/model-store:/home/model-server/model-store pytorch/torchserve:latest-gpu
```

### Model Packaing

```
torch-model-archiver --model-name insurance_chat --version 1.0 --serialized-file saved_model/conversation/pytorch_model.bin --handler ./torchserve_handler.py --export-path model-store --extra-files "saved_model/conversation/config.json"
```

### config.properties
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store

cors_allowed_origin=*
cors_allowed_methods=GET, POST, PUT, DELETE
cors_allowed_headers=X-Custom-Header
```

### Versions

pip list:
```
torch                           1.12.0+cu113
torch-model-archiver            0.6.0
torch-workflow-archiver         0.2.4
torchaudio                      0.12.0
torchmetrics                    0.9.1
torchserve                      0.6.0
torchvision                     0.13.0
```

docker images:
```
pytorch/torchserve                     latest-gpu                 fb6d4b85847d   4 weeks ago     4.49GB
```

### Repro instructions

I followed the [HuggingFace example](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers) to deploy the GPT2 model.

### Possible Solution

_No response_

### PR DESCRIPTION
**Pull request by xyang16**
## Description

Please read our [CONTRIBUTING.md](https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md) prior to creating your first pull request.

Please include a summary of the feature or issue being fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This is to fix https://github.com/pytorch/serve/issues/1740.

The cause is that the browser (tested Firefox, Chrome and Safari) was using OPTIONS to do a preflight check before PUT and DELETE request.

TS code currently doesn't handle OPTIONS for management API and will throw MethodNotAllowedException.

Fixes #1740

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Please describe the Unit or Integration tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

Before the fix the CORS DELETE / PUT requests failed with:

CORS Preflight Did Not Succeed

Screen Shot 2022-07-27 at 4 28 14 PM

After the fix the CORS requests succeeded.

Screen Shot 2022-07-27 at 4 28 30 PM

- [ ] Test B
Logs for Test B

## Checklist:

- [ ] Did you have fun?
- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [ ] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

File: frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java [hunk 1]
```diff
@@ -71,6 +71,22 @@ public static String getModelApi(Model model) {
...
+        OpenApi openApi = new OpenApi();
+        Info info = new Info();
+        info.setTitle("RESTful Management API for: " + modelName);
+        ConfigManager config = ConfigManager.getInstance();
+        info.setVersion(config.getProperty("version", null));
+        openApi.setInfo(info);
+
+        openApi.addPath("/models/{model_name}", getModelManagerPath(false));
+        openApi.addPath("/models/{model_name}/{model_version}", getModelManagerPath(true));
+        openApi.addPath("/models/{model_name}/{model_version}/set-default", getSetDefaultPath());
```
Comment (lxning) [inline frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java:85]: listManagementApis can be applied here.

Comment (xyang16) [reply frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java:85]: listManagementApis has 6 paths:

/
/models
/models/{model_name}
/models/{model_name}/{model_version}
/models/{model_name}/{model_version}/set-default
/api-description

Here because it's only listing for specific model, it has only 3 paths:

/models/{model_name}
/models/{model_name}/{model_version}
/models/{model_name}/{model_version}/set-default

**Review by lxning — APPROVED** [review]

**Review by maaquib — CHANGES_REQUESTED** [review]
Please add a unit test case as well

**Comment by xyang16** [comment]
> Please add a unit test case as well

Hi Aaqib, I have added unit tests.

**Review by maaquib — APPROVED** [review]
