### PR TITLE
Error handling - non ssl request

### LINKED ISSUE #202: SSL-enabled TorchServe handles http: protocol incorrectly
If you're running a TorchServe installation with the following config:
```
inference_address=https://0.0.0.0:8443
management_address=https://0.0.0.0:8444
keystore=keystore.p12
keystore_pass=asdfasdf
keystore_type=PKCS12
```

And you attempt an `http` call - *not* `https` - such as:
```
curl -X POST "http://localhost:8444/models?url=r18ts.mar&initial_workers=1"
```

There is no response, and an exception shows in the log:
```
2020-04-15 17:04:46,302 [ERROR] epollEventLoopGroup-3-2 org.pytorch.serve.http.HttpRequestHandler -
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f6d6f64656c733f75726c3d72313874732e6d617226696e697469616c5f776f726b6572733d3120485454502f312e310d0a486f73743a206c6f63616c686f73743a383434340d0a557365722d4167656e743a206375726c2f372e36302e300d0a4163636570743a202a2f2a0d0a0d0a
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f6d6f64656c733f75726c3d72313874732e6d617226696e697469616c5f776f726b6572733d3120485454502f312e310d0a486f73743a206c6f63616c686f73743a383434340d0a557365722d4167656e743a206375726c2f372e36302e300d0a4163636570743a202a2f2a0d0a0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1156)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 14 more
```

**Suggested Remediation:**
* Handle this case without throwing an exception, as it is something that is likely to happen during normal operation.
* Log an informative error message, perhaps in `access_log.log`.
* Give a useful error message in an HTTP response to the user, e.g., "This TorchServe instance only accepts HTTPS requests.', with a response code of 403.

### PR DESCRIPTION
**Pull request by dhaniram-kshirsagar**
## Description

Fixed issue to gracefully handle HTTP request i.e. return 403 on HTTPS server per #202.
NOTE - The first solution has been implemented i.e. return 403 with an error message instead of redirecting it.

Fixes #202 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

Tested this with the following configuration -
1. config file with http
2. config file with https
3. no config file

- Logs
[http_https_test.log](https://github.com/pytorch/serve/files/4695120/http_https_test.log)

## Checklist:

- [X] Have you added tests that prove your fix is effective or that this feature works?
- [X] New and existing unit tests pass locally with these changes?
- [X] Has code been commented, particularly in hard-to-understand areas?
- [] Have you made corresponding changes to the documentation?

### CODE REVIEW

File: frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java [hunk 1]
```diff
@@ -655,6 +661,18 @@ public boolean isSnapshotDisabled() {
         return snapshotDisabled;
     }
 
+    public boolean isSSLEnabled() {
+        String inferenceAddress = prop.getProperty(TS_INFERENCE_ADDRESS, "http://127.0.0.1:8080");
```
Comment (chauhang) [inline frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:665]: @dhaniram-kshirsagar Why is the url hardcoded here? Can we remove it?

Comment (dhaniram-kshirsagar) [reply frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:661]: This is the default value (i.e. http) for the cases when the user has not supplied any address via config or env properties.

Comment (maaquib) [reply frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:661]: Can there be a mix of ssl and non ssl endpoints e.g. `http://127.0.0.1:8080` and `https://127.0.0.1:8444`? Either we should clarify or handle that case

File: frontend/server/src/main/java/org/pytorch/serve/http/ExtendedSSLHandler.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+import java.util.List;
+import org.pytorch.serve.util.ConfigManager;
+import org.pytorch.serve.util.NettyUtils;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public class ExtendedSSLHandler extends OptionalSslHandler {
+    private static final Logger logger = LoggerFactory.getLogger(ExtendedSSLHandler.class);
+    /** the length of the ssl record header (in bytes) */
+    private static final int SSL_RECORD_HEADER_LENGTH = 5;
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/http/ExtendedSSLHandler.java:18]: Use `io.netty.handler.ssl.SslUtils.SSL_RECORD_HEADER_LENGTH` instead

Comment (dhaniram-kshirsagar) [reply frontend/server/src/main/java/org/pytorch/serve/http/ExtendedSSLHandler.java:18]: Tried that earlier however it is not visible[protected] netty.

**Comment by dhaniram-kshirsagar** [comment]
> Can you also add a unit test case

Sure.

Can please elaborate on you second comment - 
>Can there be a mix of ssl and non ssl endpoints e.g. http://127.0.0.1:8080 and https://127.0.0.1:8444? Either we > >should clarify or handle that case

File: frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java (hunk 1 above)
Comment (dhaniram-kshirsagar) [reply frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:661]: @maaquib can you please elaborate on this.

**Comment by maaquib** [comment]
> > Can you also add a unit test case
> 
> Sure.
> 
> Can you please elaborate on your second comment -
> 
> > Can there be a mix of ssl and non ssl endpoints e.g. http://127.0.0.1:8080 and https://127.0.0.1:8444? Either we > >should clarify or handle that case

Should we allow `config.properties` like the following
```
inference_address=http://127.0.0.1:8080
management_address=https://127.0.0.1:8444
```

File: frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java (hunk 1 above)
Comment (chauhang) [reply frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:661]: @dhaniram-kshirsagar We now have 3 endpoints for TS -- Management API, Inference API, Metrics API. If user selects combination of http/https across the three will that be supported? It will be better to have all endpoints of same type

**Review by HamidShojanazeri — APPROVED** [review]

**Review by lxning — APPROVED** [review]

**Comment by lxning** [comment]
@dhaniram-kshirsagar, could you please fix the conflicts?

**Comment by maaquib** [comment]
@dhaniram-kshirsagar Pinging for merge conflicts and https://github.com/pytorch/serve/pull/407#issuecomment-661250019

**Comment by maaquib** [comment]
> @dhaniram-kshirsagar Pinging for merge conflicts and [#407 (comment)](https://github.com/pytorch/serve/pull/407#issuecomment-661250019)

@dhaniram-kshirsagar Ping

**Comment by harshbafna** [comment]
> > @dhaniram-kshirsagar Pinging for merge conflicts and [#407 (comment)](https://github.com/pytorch/serve/pull/407#issuecomment-661250019)
> 
> @dhaniram-kshirsagar Ping

@maaquib: Done.

**Comment by maaquib** [comment]
We still haven't resolved the approach for https://github.com/pytorch/serve/pull/407#issuecomment-661250019
Moving this to v0.4.0

**Comment by lxning** [comment]
@maaquib @chauhang i updated the pr to address your comments. Could you pls review it? Thanks.

**Comment by maaquib** [comment]
@lxning Thanks for fixing this. Can we also add a unit test case for this or logs of an HTTP request against an ssl endpoint

**Comment by lxning** [comment]
@maaquib attached the test result
[log.txt](https://github.com/pytorch/serve/files/6160053/log.txt)

**Review by maaquib — APPROVED** [review]

File: frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java [hunk 3]
```diff
@@ -718,6 +724,30 @@ public boolean isSnapshotDisabled() {
         return snapshotDisabled;
     }
 
+    public boolean isSSLEnabled(ConnectorType connectorType) {
+        String address = prop.getProperty(TS_INFERENCE_ADDRESS, "http://127.0.0.1:8080");
```
Comment (chauhang) [inline frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:728]: @dhaniram-kshirsagar  Why are the port numbers hard coded here? As these are configurable, how are things expected to work if the user picked other port numbers? Same comment for the other port numbers

**Review by chauhang — CHANGES_REQUESTED** [review]
Please see comments inline

File: frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java (hunk 3 above)
Comment (lxning) [reply frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java:728]: the hard coded port is default port. It is used only if user doesn't customize the ports.

**Review by chauhang — APPROVED** [review]
