### PR TITLE
Fixed: Model reader logging bugs.

### LINKED ISSUE #727: Logging in custom handler?
It looks like at the moment any logs output in a custom handler will be read from the stdout of the process running the handler, then output at level INFO from the thread managing the worker life cycle (in this class (?): https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java). Logging in custom handlers is useful in cases of more complex inference 

This makes it difficult to send accurate/well formatted logs from a custom handler to the stdout of its parent process. In particular, it forces one to use a log level INFO even if one is only interested in ERROR logs from the handler. It also means that any formatting rules applied in the java level will be applied on top of the rules applied at the handler level, making consistent log outputs of any complexity difficult.

Is there a better way to accomplish logging in the custom handlers? Since arbitrarily many workers could be serving a single model, it would be difficult to even use file based logging to collect the log outputs related to a model.

### PR DESCRIPTION
**Pull request by aparmentier-coveo**
## Description

The lines read from the stdout/stderr of the handler will now be logged on a distinct logger (the MODEL_LOG). This will give much finer grained control over logging in custom handlers. For example, the log4j settings for MODEL_LOG can be set to log everything with no formatting, giving complete control of the logging situation to the custom handler. 

I believe this is the intended use of the MODEL_LOGGER logger name. Currently it is not used.

In addition, the metrics logger is now initialized via a sl4j logging factory rather than through log4j. The call to log metrics was slightly modified to fit with this more generic logger which only accepts String arguments.

Fixes #727

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Feature/Issue validation/testing

A unit test for the MODEL_LOG already exists, but no code in the server actually used this logger.

## Checklist:

- [ ] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [ ] Have you made corresponding changes to the documentation?

### CODE REVIEW

**Comment by chauhang** [comment]
@aparmentier-coveo Please attach unit test logs -- ie the output logs after these changes

**Comment by aparmentier-coveo** [comment]
I'm not sure exactly which logs you mean (there's a whole logs directory created by running the UTs), but here is the piped output from the sanity script. Note, I don't have CUDA set up.

[unit_test_output.txt](https://github.com/pytorch/serve/files/5604492/unit_test_output.txt)

**Comment by aparmentier-coveo** [comment]
Is there something missing for this PR? Anything I can do to get it moving along?

**Comment by maaquib** [comment]
@aparmentier-coveo We are currently busy with 0.3.0 release. I have added this to 0.4 release and will have this reviewed

File: frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java [hunk 1]
```diff
@@ -141,8 +141,10 @@ private synchronized void setPort(int port) {
         private boolean error;
         private WorkerLifeCycle lifeCycle;
         private AtomicBoolean isRunning = new AtomicBoolean(true);
-        private static final org.apache.log4j.Logger loggerModelMetrics =
-                org.apache.log4j.Logger.getLogger(ConfigManager.MODEL_METRICS_LOGGER);
+        private static final Logger loggerModelMetrics =
+                LoggerFactory.getLogger(ConfigManager.MODEL_METRICS_LOGGER);
+        private static final Logger loggerModelOutput =
+                LoggerFactory.getLogger(ConfigManager.MODEL_LOGGER);
```
Comment (lxning) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: These changes store model log in separate log files. It is much easier for user to control model log format. The only problem is that the mapping information b/w frontend worker thread id and backend worker pid is missing. It will be difficult to debug TS to detect if there is sth wrong with frontend worker thread.

Comment (aparmentier-coveo) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: Hi, thanks for having a look. Where do you think the PID message should end up?

Comment (aparmentier-coveo) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: Oh I see, thank you. I think that would just be a change to the log4j default settings for the MODEL_LOG. I'll experiment and probably update this PR tomorrow.

Comment (lxning) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: Thanks a lot.

Comment (aparmentier-coveo) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: I rebased and updated the default logging pattern format for MODEL_LOG to be the same as the other logs which include a thread name.

Cheers,

Alex

**Comment by lxning** [comment]
test results:
model-server@d8d60d508f28:~/logs$ cat model_log.log
2021-03-18 03:10:42,141 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9001
2021-03-18 03:10:42,143 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - [PID]45
2021-03-18 03:10:42,143 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - Torch worker started.
2021-03-18 03:10:42,144 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - Python runtime: 3.6.9
2021-03-18 03:10:42,152 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2021-03-18 03:10:42,153 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - [PID]46
2021-03-18 03:10:42,153 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - Torch worker started.
2021-03-18 03:10:42,154 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - Python runtime: 3.6.9
2021-03-18 03:10:42,170 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2021-03-18 03:10:42,170 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9001.
2021-03-18 03:10:43,059 [INFO ] W-9000-vgg11_v2_1.0-stdout MODEL_LOG - Generating new fontManager, this may take some time...
2021-03-18 03:10:43,105 [INFO ] W-9001-vgg11_v2_1.0-stdout MODEL_LOG - Generating new fontManager, this may take some time...
model-server@d8d60d508f28:~/logs$ cat model_metrics.log
2021-03-18 03:11:31,747 - HandlerTime.Milliseconds:30.7|#ModelName:vgg11_v2,Level:Model|#hostname:d8d60d508f28,requestID:c69ca44f-ca2b-418e-8673-e72f9db64600,timestamp:1616037091
2021-03-18 03:11:31,748 - PredictionTime.Milliseconds:30.8|#ModelName:vgg11_v2,Level:Model|#hostname:d8d60d508f28,requestID:c69ca44f-ca2b-418e-8673-e72f9db64600,timestamp:1616037091

File: frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java (hunk 1 above)
Comment (lxning) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java:148]: It works. Thank you!

**Review by lxning — APPROVED** [review]

**Review by dhanainme — APPROVED** [review]

**Comment by Noman-Tanveer** [comment]
Guys, It always downgrades the model logs of model to [INFO] level even if I'm logging it as "error" or "critical". Is there a way to get right level for logging.
