### PR TITLE
Correct pythonpath for pip dependency installation

### LINKED ISSUE #1130: Custom Requirements installation failed
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

We are using torchserve to deploy, predict and explain pytorch lightning models in kubelow.

For the inference service, we are using the official docker hub image - `pytorch/torchserve-kfs:0.4.0`

Since the docker image doen't contain `pytorch-lightning` package. We are added it in `requirements.txt` and bundling it using `torch-model-archiver`. 

When `install_py_dep_per_model` is set to `true` the packages listed in the `requirements.txt` are **not getting installed**. The issue is getting reproduced in both standalone and docker images.

* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0
* torch version: 1.8.1
* torchvision version [if any]: 0.9.1
* torchtext version [if any]: 0.9.1
* torchaudio version [if any]:
* java version: 
ubuntu@ubuntu-ThinkPad-L490:~/Documents/facebook/phase2/mlflow-torchserve/examples/IrisClassification$ java --version
openjdk 11.0.11-ea 2021-04-20
OpenJDK Runtime Environment (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1)
OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1, mixed mode, sharing)

* Operating System and version: Ubuntu - 16.04

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom
* What kind of model is it e.g. vision, text, audio?: vision/text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior
When `install_py_dep_per_model` is set to `true`, pytorch lightning should be installed and model should load successfully.

## Current Behavior
when `install_py_dep_per_model` is set to `true`, torchserve is throwing the error (attached logs)

It is strange that, even if `pytorch_lightning` is present in the environment and `install_py_dep_per_model` is set to `true`, the same error is getting reproduced.

## Steps to Reproduce

[iris.zip](https://github.com/pytorch/serve/files/6677618/iris.zip)

1. Unzip iris.zip - It contains `iris.mar` and `config.properties` file
2. Create a directory `model-store`
3. copy iris.mar inside `model-store`
4. set `install_py_dep_per_model=false` in config.properties
5. Install pytorch lightning using pip - `pip install pytorch_lightning==1.3.2`
5. start torchserve with following command
`torchserve --start --ts-config config.properties`
6. Model will be loaded successfully.
7. Stop the torchserve - `torchserve --stop`
8. Uninstall pytorch lightining using `pip uninstall pytorch-lightning`
9. set `install_py_dep_per_model` to true now.
10. start torchserve with following command
`torchserve --start --ts-config config.properties`

## Failure Logs [if any]
Failure logs are attached in ts-failure.txt
[ts-failure.txt](https://github.com/pytorch/serve/files/6677666/ts-failure.txt)

Success scenario log
[ts-success.txt](https://github.com/pytorch/serve/files/6677678/ts-success.txt)

### PR DESCRIPTION
**Pull request by nskool**
## Description
1. This change enables printing of error messages published to stdout or stderr by the 'python pip package installation' process.
2. It also corrects pythonPath used when installing a dependency package, while registering the model for the first time.

Fixes #1130 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

Please describe the tests [UT/IT] that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced. 
Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

- UT/IT execution results

- Logs
Following from issue #1130 , the following command succeeds:
```
torchserve --start --models iris=iris-new.mar --model-store ./benchmarks/model_store --ts-config ./benchmarks/model_store/config.properties 2>&1 > ~/torchserve.log
```
Caveat: The requirements.txt file must have the following contents:
```
torchtext
pytorch-lightning==1.3.2
```

When a package installation fails, the output is detailed as:
```
2021-06-29 20:39:56,703 [INFO ] main org.pytorch.serve.wlm.ModelManager - Dependency installation stdout:

2021-06-29 20:39:56,703 [ERROR] main org.pytorch.serve.wlm.ModelManager - Dependency installation stderr:
ERROR: Could not find a version that satisfies the requirement axyasdfazebbra (from versions: none)ERROR: No matching distribution found for axyasdfazebbra
2021-06-29 20:39:56,704 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: iris-new.mar
org.pytorch.serve.archive.model.ModelException: Custom pip package installation failed for iris
        at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:249)
        at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:150)
        at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:234)
        at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:340)
        at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:117)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:98)
```

## Checklist:

- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 1]
```diff
@@ -211,15 +214,34 @@ private void setupModelDependencies(Model model)
...
             int exitCode = process.waitFor();
+
             if (exitCode != 0) {
+
+                String line;
+                // process's stdout is InputStream for caller process
+                logger.error("Dependency installation stdout:");
+                BufferedReader brdr = new BufferedReader(new InputStreamReader(process.getInputStream()));
+                while((line = brdr.readLine()) != null) {
+                    System.out.println(line);
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:235]: NIT: Instead of the print these here, it would be better to append this to `ModelException` that is thrown below

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 2]
```diff
@@ -145,11 +147,12 @@ public ModelArchive registerModel(
...
         }
 
-        logger.info("Model {} loaded.", tempModel.getModelName());
 
         setupModelDependencies(tempModel);
 
-        return archive;
+        logger.info("Model {} loaded.", tempModel.getModelName());
+
+	return archive;
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:155]: NIT: indentation

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 3]
```diff
@@ -211,15 +214,34 @@ private void setupModelDependencies(Model model)
                             + requirementsFilePath; // NOPMD
 
             String[] envp =
-                    EnvironmentUtils.getEnvString(configManager.getModelServerHome(), null, null);
+                    EnvironmentUtils.getEnvString(model.getModelDir().getAbsolutePath(), null, null);
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:217]: I think getting the path from configManager was done purposefully so that a customer can provide a non-default python path. I am surprised there are no unit test failing for this change

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 1 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:235]: Makes sense, will add.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 2 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:155]: Will fix.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 3 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: Actually No unit tests are failing due to change. I'm suggesting this change because of the following reasons: In other places where getEnvString() is called (e.g., [here](https://github.com/pytorch/serve/blob/4f7349a13e98a1f44f76db01af976ed00da5d468/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java#L60) and [here](https://github.com/pytorch/serve/blob/f0da8d2714628cb5de0c6eaa3ac0448a6b226640/frontend/server/src/main/java/org/pytorch/serve/metrics/MetricCollector.java#L40) ) the 'cwd' argument is being set to the temporary closure of the model i.e. '/tmp/models/<random_id>'. So using 'configManager.getModelServerHome()' location seems like an anomaly in the setupModelDependencies function. 

Also, the value of 'configManager.getModelServerHome()' has the string 'site-packages' in it, which results in the value NOT being added to the PYTHONPATH as per this [line](https://github.com/pytorch/serve/blob/a95ef13eb735efba6168ed485d7ab943f5e65ac3/frontend/server/src/main/java/org/pytorch/serve/util/messages/EnvironmentUtils.java#L44). So the value seems to be wasted.

I don't see how using configManager.getModelServerHome() is allowing customers to provide a non-default path. It's value on an Ubuntu instance is: `configManager.getModelServerHome(): /home/ubuntu/test/lib/python3.6/site-packages`, whereas the value of model.getModelDir().getAbsolutePath() looks like: `model.getModelDir().getAbsolutePath(): /tmp/models/6615713b803846919386a82102e4fbed`.

This line change doesn't change anything significant as of now, and is introduced more for consistency and correctness, than for fixing a specific bug.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 4]
```diff
@@ -211,15 +213,36 @@ private void setupModelDependencies(Model model)
...
+                        new BufferedReader(new InputStreamReader(process.getInputStream()));
+                while ((line = brdr.readLine()) != null) {
+                    System.out.println(line);
+                }
+
+                // process's stderr is ErrorStream for caller process
+                logger.info("Dependency installation stderr:");
+                brdr = new BufferedReader(new InputStreamReader(process.getErrorStream()));
+                while ((line = brdr.readLine()) != null) {
+                    System.out.println(line);
```
Comment (lxning) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:243]: same here.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: I've added the stdout and stderr to the logger.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 5]
```diff
@@ -211,15 +214,34 @@ private void setupModelDependencies(Model model)
...
+                BufferedReader brdr = new BufferedReader(new InputStreamReader(process.getInputStream()));
+                while((line = brdr.readLine()) != null) {
+                    System.out.println(line);
+                }
+
+                // process's stderr is ErrorStream for caller process
+                logger.info("Dependency installation stderr:");
+                brdr = new BufferedReader(new InputStreamReader(process.getErrorStream()));
+                while((line = brdr.readLine()) != null) {
+                        System.out.println(line);
```
[the remark this answers is not in the document]
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: I've added the stdout and stderr to the logger.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 4 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: I've added the stdout and stderr to the logger.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 3 above)
Comment (lxning) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: "site-packages" is included in pip default value. That's why 'configManager.getModelServerHome()' has the string 'site-packages' in it. This value can be changed if "model_server_home" is set in property file. 

The sanity test didn't fall because [config_test_env.properties](https://github.com/pytorch/serve/blob/master/frontend/server/src/test/resources/#L6) and [config.properties](https://github.com/pytorch/serve/blob/master/frontend/server/src/test/resources/config.properties#L6) unset "model_server_home".

I think both configManager.getModelServerHome() and model.getModelDir().getAbsolutePath() should be added in pythonpath.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 6]
```diff
@@ -211,15 +213,38 @@ private void setupModelDependencies(Model model)
...
                                     packageInstallCommand,
                                     envp,
                                     model.getModelDir().getAbsoluteFile());
+
             int exitCode = process.waitFor();
+
             if (exitCode != 0) {
+
+                String line;
+                String outputString = "";
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:231]: Use `StringBuilder` instead

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java [hunk 7]
```diff
@@ -211,15 +213,38 @@ private void setupModelDependencies(Model model)
...
+                brdr = new BufferedReader(new InputStreamReader(process.getErrorStream()));
+                while ((line = brdr.readLine()) != null) {
+                    errorString += line;
+                }
+
+                logger.info("Dependency installation stdout:\n" + outputString);
+                logger.error("Dependency installation stderr:\n" + errorString);
+
                 throw new ModelException(
                         "Custom pip package installation failed for " + model.getModelName());
```
Comment (maaquib) [inline frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:249]: NIT: Consider appending the error trace to this exception instead

**Review by maaquib — CHANGES_REQUESTED** [review]

**Review by HamidShojanazeri — APPROVED** [review]

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 7 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:251]: This causes unit tests such as https://github.com/pytorch/serve/blob/master/frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java#L999 to fail, since they've been written for a specific package. The pip installation failure log in case of a package is a long trace that could be different most of the times. I'd like to retain the test because it's useful in it's current form, while adding the failure as an error log.

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 6 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: Done

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 3 above)
Comment (nskool) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java]: Done

File: frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java (hunk 7 above)
Comment (maaquib) [reply frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java:251]: We can append "Custom pip package installation failed for" to the error message and change the unit test to assert string contains instead of string equals

**Review by maaquib — APPROVED** [review]
