### PR TITLE
Fixed response status message for inferencing on model with zero workers

### LINKED ISSUE #29: Update error message when attempting inference on model with 0 workers
On adding a model via the management-api, the default min/max workers for the model is set to 0. As a result when running prediction against the model after registering gives a 503 error with details as 'No worker is available to serve request: densenet161'. This will be confusing for user's trying to add models from the inference api. 

**Register model using:**  
curl -X POST "http://<torchserve-host>:<mgmt-port>/models?url=https://<s3_path>/densenet161.mar"
{
  "status": "Model densenet161 registered"
}

**Inference using:** 
curl -X POST http://<torchserve-host>:<inf-port>/predictions/densenet161 -T cutekit.jpeg
{
  "code": 503,
  "type": "ServiceUnavailableException",
  "message": "No worker is available to serve request: densenet161"
}

**Model details:** 
curl -X GET http://<torchserve-host>:<mgmt-port>/models/densenet161
[
  {
    "modelName": "densenet161",
    "modelVersion": "1.0",
    "modelUrl": "https://<s3-bucket-url>/densenet161.mar",
    "runtime": "python",
    "minWorkers": 0,
    "maxWorkers": 0,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": false,
    "workers": []
  }
]

### PR DESCRIPTION
**Pull request by mjpsl**
## Description

Update error message when attempting inference on model with 0 workers

Fixes #29 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

 -[x] Test 1: Register model with 0 initial_workers Asynchronously
	curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/resnet-18.mar&synchronous=false"
	{
	  "status": "Model \"resnet-18\" Version: 1.0 registered with 0 initial workers. Use scale API to add workers for the model."
	}
	
 -[x] Test 2: Register model with 0 initial_workers Synchronously
	curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/densenet161.mar&synchronous=true"
	{
	  "status": "Model \"densenet161\" Version: 1.0 registered with 0 initial workers. Use scale API to add workers for the model."
	}
	
 -[x] Test 3: Register model with 3 initial_workers Synchronously
	curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/squeezenet1_1.mar&initial_workers=3&synchronous=true"
	{
	  "status": "Model \"squeezenet1_1\" Version: 1.0 registered with 3 initial workers"
	}
 -[x] Test 4: Register model with 3 initial_workers Asynchronously
	curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/densenet161.mar&initial_workers=3&synchronous=false"
	{
	  "status": "Processing worker updates..."
	}

 -[x] Test 5: Inference on model which has 0 workers
	curl  -X POST http://127.0.0.1:8080/predictions/resnet-18 -T kitten.jpg
	{
	  "code": 503,
	  "type": "ServiceUnavailableException",
	  "message": "Model \"resnet-18\"  has no worker to serve inference request. Please use scale workers API to add workers."
	}

 -[x] Test 6: Inference on model which has workers 
	curl  -X POST http://127.0.0.1:8080/predictions/densenet161 -T kitten.jpg
[torchserve_sanity.log](https://github.com/pytorch/serve/files/4591493/torchserve_sanity.log)

	[
	  {
		"tiger_cat": 0.4693359136581421
	  },
	  {
		"tabby": 0.4633873701095581
	  },
	  {
		"Egyptian_cat": 0.06456154584884644
	  },
	  {
		"lynx": 0.001282821292988956
	  },
	  {
		"plastic_bag": 0.00023323031200561672
	  }
	]
 -[x] Test 7: Scale Mode with non zero workers
   curl -X PUT "http://localhost:8081/models/resnet-18?min_worker=5&max_worker=10&synchronous=true"
    {
      "status": "5 Workers scaled for model resnet-18"
    }

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?

### CODE REVIEW

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 1]
```diff
@@ -238,8 +238,11 @@ private void handleRegisterModel(
 
         modelName = archive.getModelName();
 
-        final String msg = "Model \"" + modelName + "\" registered";
         if (initialWorkers <= 0) {
+            final String msg =
+                    "Model \""
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:243]: Add model version as well in response.

File: frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java [hunk 2]
```diff
@@ -179,7 +179,9 @@ private void predict(
         Job job = new Job(ctx, modelName, modelVersion, WorkerCommands.PREDICT, input);
         if (!ModelManager.getInstance().addJob(job)) {
             throw new ServiceUnavailableException(
-                    "No worker is available to serve request: " + modelName);
+                    "No worker is available to serve request: "
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java:182]: Add model version as well in response.

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 3]
```diff
@@ -329,8 +335,19 @@ private void updateModelWorkers(
...
+                                        String msg =
+                                                "Model \""
+                                                        + modelName
+                                                        + "\" registered with "
+                                                        + minWorkers
+                                                        + " initial workers";
+                                        NettyUtils.sendJsonResponse(
+                                                ctx, new StatusResponse(msg), v);
+                                    } else {
+                                        NettyUtils.sendJsonResponse(
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:348]: create message string in the if else block and use a common statement to return the response. Add model version as well in response for model registration call.

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 4]
```diff
@@ -311,7 +316,8 @@ private void updateModelWorkers(
             int minWorkers,
             int maxWorkers,
             boolean synchronous,
-            final Function<Void, Void> onError) {
+            final Function<Void, Void> onError,
+            boolean isRegistration) {
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:320]: rename as isModelRegistrationRequest

Comment (harshbafna) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:320]: move this argument before onError.

File: frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java (hunk 2 above)
Comment (dhaniram-kshirsagar) [reply frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java:182]: Can we say here 'Model {} has no worker to serve inference request'?

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 5]
```diff
@@ -329,8 +335,19 @@ private void updateModelWorkers(
...
+                                                "Model \""
+                                                        + modelName
+                                                        + "\" registered with "
+                                                        + minWorkers
+                                                        + " initial workers";
+                                        NettyUtils.sendJsonResponse(
+                                                ctx, new StatusResponse(msg), v);
+                                    } else {
+                                        NettyUtils.sendJsonResponse(
+                                                ctx, new StatusResponse("Workers scaled"), v);
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:349]: Improve message to contain number of workers, model name and version.

File: frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java [hunk 6]
```diff
@@ -179,7 +179,12 @@ private void predict(
         Job job = new Job(ctx, modelName, modelVersion, WorkerCommands.PREDICT, input);
         if (!ModelManager.getInstance().addJob(job)) {
             throw new ServiceUnavailableException(
-                    "No worker is available to serve request: " + modelName);
+                    "Model \""
+                            + modelName
+                            + "\" Version "
+                            + modelVersion
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java:185]: Add a null check for modelVersion and return default version in that case.

Comment (mjpsl) [reply frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java:188]: Now instead of null, it will show defaultVersion

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 7]
```diff
@@ -329,8 +337,19 @@ private void updateModelWorkers(
                                     modelManager.scaleRequestStatus(modelName, modelVersion);
                             if (HttpResponseStatus.OK.equals(v)) {
                                 if (status) {
-                                    NettyUtils.sendJsonResponse(
-                                            ctx, new StatusResponse("Workers scaled"), v);
+                                    String msg =
```
Comment (vdantu) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:340]: I am curious to understand if this message needs modification. Can't this be a generic message of how many workers are we scaling this to? If we elaborate on this message, then customers who maintain logs will know that `POST /models`, which is register model,  was updated with `n` number of workers. Adding a flag to determine the code path, ie., if this is coming from register-model or from scale model, seems a little hacky.

Comment (dhaniram-kshirsagar) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:340]: The idea is to keep the response message consistent for registration request with/without initial workers. I agree its a bit hacky.

Comment (mjpsl) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:340]: Keeping these changes as message give clear information.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java [hunk 8]
```diff
@@ -123,13 +123,13 @@ public void test()
...
         testUnregisterModel(managementChannel, "noop", null);
-        testLoadModel(managementChannel, "noop.mar", "noop_v1.0");
+        testLoadModel(managementChannel, "noop.mar", "noop_v1.0", "1.11");
         testSyncScaleModel(managementChannel, "noop_v1.0", null);
         testListModels(managementChannel);
         testDescribeModel(managementChannel, "noop_v1.0", null, "1.11");
-        testLoadModelWithInitialWorkers(managementChannel, "noop.mar", "noop");
-        testLoadModelWithInitialWorkers(managementChannel, "noop.mar", "noopversioned");
-        testLoadModelWithInitialWorkers(managementChannel, "noop_v2.mar", "noopversioned");
+        testLoadModelWithInitialWorkers(managementChannel, "noop.mar", "noop", "1.11");
```
Comment (harshbafna) [inline frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:130]: remove the versions from the UT. This should not be required while loading a model.

File: frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java [hunk 9]
```diff
@@ -178,8 +178,23 @@ private void predict(
 
         Job job = new Job(ctx, modelName, modelVersion, WorkerCommands.PREDICT, input);
         if (!ModelManager.getInstance().addJob(job)) {
-            throw new ServiceUnavailableException(
-                    "No worker is available to serve request: " + modelName);
+            String responseMessage =
+                    "Model \""
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/InferenceRequestHandler.java:182]: Remove duplication for common string in both the responses.

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java [hunk 10]
```diff
@@ -329,8 +337,19 @@ private void updateModelWorkers(
...
+                                            minWorkers + " Workers scaled for model " + modelName;
```
Comment (harshbafna) [inline frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:341]: Add version in response.

**Comment by dhaniram-kshirsagar** [comment]
Please resolve conflict, rest looks fine.

**Comment by harshbafna** [comment]
Validated all the scale worker and registration API and working as expected.

Logs :

[install_from_source_29.txt](https://github.com/pytorch/serve/files/4669271/install_from_source_29.txt)
[test_apis.txt](https://github.com/pytorch/serve/files/4669273/test_apis.txt)

File: frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java (hunk 7 above)
Comment (maaquib) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:344]: @vdantu Let me know if this LGTY

Comment (vdantu) [reply frontend/server/src/main/java/org/pytorch/serve/http/ManagementRequestHandler.java:344]: I am still not convinced that passing a boolean flag to determine the error message is the the only option. But, this is is **not** a blocker for the PR. We can look into how to refactor this code in the future (may be return the `future` to the method above and populate the error message there or some such).
