### PR TITLE
Corrected port number validation range

### LINKED ISSUE #291: Invalid Port while running inside a PaaS
[HERE](https://github.com/pytorch/serve/blob/1f16a7e5989e046f0e5ce5a9f4c73182f63c4573/frontend/server/src/main/java/org/pytorch/serve/util/Connector.java#L108) there is a validation for port being less than or equal to `Short.MAX_VALUE`

**Possible Fix**:
Change the validation to `PORT <= 2*Short.MAX_VALUE + 1`  i.e. 65535 being the upper limit for PORT.

**Failure with PORT = 42523**
```
2020-05-01T02:36:00.546027+00:00 app[web.1]: 2020-05-01 02:36:00,545 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
2020-05-01T02:36:00.546355+00:00 app[web.1]: Invalid configuration: Invalid port number: http://0.0.0.0:42523
2020-05-01T02:36:00.558874+00:00 app[web.1]: Exception in thread "Thread-0" java.lang.NullPointerException
2020-05-01T02:36:00.559051+00:00 app[web.1]: 	at org.pytorch.serve.ModelServer.stop(ModelServer.java:374)
2020-05-01T02:36:00.559131+00:00 app[web.1]: 	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:79)
```

**Success with PORT = 18229**
```
2020-05-01T02:36:34.820448+00:00 app[web.1]: 2020-05-01 02:36:34,819 [INFO ] main org.pytorch.serve.ModelServer - 
2020-05-01T02:36:34.820471+00:00 app[web.1]: TS Home: /usr/local/lib/python3.6/dist-packages
2020-05-01T02:36:34.820471+00:00 app[web.1]: Current directory: /home/model-server
2020-05-01T02:36:34.820472+00:00 app[web.1]: Temp directory: /home/model-server/tmp
2020-05-01T02:36:34.820472+00:00 app[web.1]: Number of GPUs: 0
2020-05-01T02:36:34.820472+00:00 app[web.1]: Number of CPUs: 8
2020-05-01T02:36:34.820472+00:00 app[web.1]: Max heap size: 15362 M
2020-05-01T02:36:34.820473+00:00 app[web.1]: Python executable: /usr/bin/python3
2020-05-01T02:36:34.820473+00:00 app[web.1]: Config file: /home/model-server/config.properties
2020-05-01T02:36:34.820473+00:00 app[web.1]: Inference address: http://0.0.0.0:18229
2020-05-01T02:36:34.820473+00:00 app[web.1]: Management address: http://0.0.0.0:8081
2020-05-01T02:36:34.820474+00:00 app[web.1]: Model Store: /home/model-server/model-store
2020-05-01T02:36:34.820474+00:00 app[web.1]: Initial Models: all
2020-05-01T02:36:34.820474+00:00 app[web.1]: Log dir: /home/model-server/logs
2020-05-01T02:36:34.820474+00:00 app[web.1]: Metrics dir: /home/model-server/logs
2020-05-01T02:36:34.820474+00:00 app[web.1]: Netty threads: 4
2020-05-01T02:36:34.820474+00:00 app[web.1]: Netty client threads: 4
2020-05-01T02:36:34.820475+00:00 app[web.1]: Default workers per model: 1
2020-05-01T02:36:34.820475+00:00 app[web.1]: Blacklist Regex: N/A
2020-05-01T02:36:34.820475+00:00 app[web.1]: Maximum Response Size: 6553500
2020-05-01T02:36:34.820475+00:00 app[web.1]: Maximum Request Size: 6553500
```

### PR DESCRIPTION
**Pull request by shivamshriwas**
## Description

Corrected the port range to upper limit of valid port range ie 65535.
Added UT for the scenario.

Fixes #291 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Feature/Issue validation/testing

- [x] Test A
Run torchserve on valid port range eg: 8081,42523 (1024 - 65535)

- UT/IT execution results

- Logs
[issue_291_torchserve_sanity_log.txt](https://github.com/pytorch/serve/files/4598683/issue_291_torchserve_sanity_log.txt)

## Checklist:

- [x] Have you added tests that prove your fix is effective or that this feature works?
- [x] New and existing unit tests pass locally with these changes?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

### CODE REVIEW

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java [hunk 1]
```diff
@@ -1244,4 +1247,43 @@ private void testMetricManager() throws JsonParseException, InterruptedException
             }
         }
     }
+
+    private void testTSPortRange()
```
Comment (dhaniram-kshirsagar) [inline frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1251]: Can we add negative and edge cases for this?

File: frontend/server/src/test/resources/config.properties [hunk 2]
```diff
@@ -25,7 +25,6 @@ certificate_file=src/test/resources/certs.pem
 # max_response_size=6553500
 max_request_size=10485760
 # blacklist_env_vars=.*USERNAME.*|.*PASSWORD.*
-# enable_env_vars_config=false
```
Comment (vdantu) [inline frontend/server/src/test/resources/config.properties:28]: Why are we removing this?

File: frontend/server/src/test/resources/config_invalid_port.properties [hunk 3]
```diff
@@ -0,0 +1,5 @@
+inference_address=https://127.0.0.1:65536
+management_address=unix:/tmp/management.sock
+# model_server_home=../..
```
Comment (vdantu) [inline frontend/server/src/test/resources/config_invalid_port.properties:3]: We can remove the commented properties in test configurations.

File: frontend/server/src/test/resources/config_invalid_port.properties [hunk 4]
```diff
@@ -0,0 +1,5 @@
...
+model_store=../modelarchive/src/test/resources/models
+enable_envvars_config=true
```
Comment (vdantu) [inline frontend/server/src/test/resources/config_invalid_port.properties:5]: Do we need `inference_address` to be `true`? The configuration seems to be set in the properties file itself.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java [hunk 5]
```diff
@@ -1244,4 +1248,65 @@ private void testMetricManager() throws JsonParseException, InterruptedException
...
         }
     }
+
+    private void testTSValidPort()
+            throws InterruptedException, GeneralSecurityException, InvalidSnapshotException,
+                    IOException {
+        //  test case for verifying port range refer https://github.com/pytorch/serve/issues/291
+        server.stop();
+        System.setProperty("tsConfigFile", "src/test/resources/config_port.properties");
+        FileUtils.deleteQuietly(new File(System.getProperty("LOG_LOCATION"), "config"));
```
Comment (vdantu) [inline frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1258]: I am curious to know what this file is, that we are deleting.

Comment (harshbafna) [reply frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1258]: Due to snapshot feature, the first preference will be given to last available snapshot file instead of the properties file set in the system properties. Thus cleaning up the generated snapshot before restart.

File: frontend/server/src/test/resources/config.properties (hunk 2 above)
Comment (harshbafna) [reply frontend/server/src/test/resources/config.properties:28]: The variable name is incorrect. The correct one is already uncommented and in use in line #29 below.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java (hunk 5 above)
Comment (vdantu) [reply frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1258]: Why is snapshot given a preference over the runtime configuration? Whats the order of preference for this?

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java [hunk 6]
```diff
@@ -1244,4 +1248,65 @@ private void testMetricManager() throws JsonParseException, InterruptedException
...
+        testPing(channel);
+    }
+
+    private void testTSInvalidPort()
+            throws InterruptedException, GeneralSecurityException, InvalidSnapshotException,
+                    IOException {
+        //  test case for verifying port range refer https://github.com/pytorch/serve/issues/291
+        //  invalid port test
+        server.stop();
+        System.setProperty("tsConfigFile", "src/test/resources/config_invalid_port.properties");
```
Comment (vdantu) [inline frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1297]: I was thinking about this test a little more. Since this test is only testing hte JAVA code path, couldn't we simply modify the [TS_INFERENCE_ADDRESS](https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java#L52) property in [ConfigManager](https://github.com/pytorch/serve/blob/master/frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java#L622) and restart the server? Do we need this additional config.properties file?

File: frontend/server/src/test/resources/config.properties (hunk 2 above)
Comment (vdantu) [reply frontend/server/src/test/resources/config.properties:28]: Oh. Ok. Good catch.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java (hunk 5 above)
Comment (harshbafna) [reply frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1258]: The preference order for properties file is as follows :

 - System environment
 - Command line argument
 - Last snapshot
 - Java System Property.

File: frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java (hunk 6 above)
Comment (harshbafna) [reply frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java:1297]: +1

This is a much simpler approach. Thanks.
